import { Pick, Prop, OddsEntry, TrackedBet } from './types';

const today = new Date();
const fmt = (d: Date) => d.toISOString().split('T')[0];
const daysAgo = (n: number) => fmt(new Date(today.getTime() - n * 86400000));
const daysAhead = (n: number) => fmt(new Date(today.getTime() + n * 86400000));

export const mockPicks: Pick[] = [
  {
    id: '1',
    sport: 'NFL',
    game: 'Kansas City Chiefs vs Baltimore Ravens',
    home_team: 'Baltimore Ravens',
    away_team: 'Kansas City Chiefs',
    bet_type: 'spread',
    pick: 'Chiefs -3',
    odds: -110,
    confidence: 5,
    analysis: 'Mahomes is 12-2 ATS as a road favorite this season. Ravens secondary has been shredded by mobile QBs. Chiefs offensive line is healthy for the first time all year.',
    result: 'win',
    game_date: daysAgo(3),
    units: 2.0,
  },
  {
    id: '2',
    sport: 'NFL',
    game: 'San Francisco 49ers vs Dallas Cowboys',
    home_team: 'Dallas Cowboys',
    away_team: 'San Francisco 49ers',
    bet_type: 'moneyline',
    pick: '49ers ML',
    odds: -145,
    confidence: 4,
    analysis: 'Purdy has been elite at home, 9-1 this season. Cowboys pass rush is ranked 28th in the league. Expect McCaffrey to dominate on the ground.',
    result: 'win',
    game_date: daysAgo(3),
    units: 1.5,
  },
  {
    id: '3',
    sport: 'NBA',
    game: 'Los Angeles Lakers vs Golden State Warriors',
    home_team: 'Golden State Warriors',
    away_team: 'Los Angeles Lakers',
    bet_type: 'over/under',
    pick: 'Over 224.5',
    odds: -110,
    confidence: 4,
    analysis: 'Both teams rank bottom-10 in defensive efficiency. Warriors have gone over in 8 of their last 10 home games. Pace will be fast with Curry and Davis.',
    result: 'loss',
    game_date: daysAgo(2),
    units: 1.0,
  },
  {
    id: '4',
    sport: 'NBA',
    game: 'Boston Celtics vs Milwaukee Bucks',
    home_team: 'Milwaukee Bucks',
    away_team: 'Boston Celtics',
    bet_type: 'spread',
    pick: 'Celtics -4.5',
    odds: -110,
    confidence: 5,
    analysis: 'Tatum has been dominant on the road this year, averaging 31.2 points. Bucks are 3-8 ATS at home vs top-5 teams. Celtics defense limits Giannis in the paint.',
    result: 'win',
    game_date: daysAgo(2),
    units: 2.0,
  },
  {
    id: '5',
    sport: 'NHL',
    game: 'Colorado Avalanche vs Edmonton Oilers',
    home_team: 'Edmonton Oilers',
    away_team: 'Colorado Avalanche',
    bet_type: 'moneyline',
    pick: 'Avalanche ML',
    odds: -120,
    confidence: 4,
    analysis: 'MacKinnon leads all NHL scorers with 1.4 PPG at home. Oilers goaltending inconsistent, 3.2 GAA over last 5 games. Avs power play is lethal at 32%.',
    result: 'loss',
    game_date: daysAgo(1),
    units: 1.0,
  },
  {
    id: '6',
    sport: 'MLB',
    game: 'New York Yankees vs Houston Astros',
    home_team: 'Houston Astros',
    away_team: 'New York Yankees',
    bet_type: 'moneyline',
    pick: 'Yankees ML',
    odds: +125,
    confidence: 3,
    analysis: 'Gerrit Cole is 7-1 in his last 8 road starts vs AL opponents. Astros bullpen has a 4.8 ERA over the last 2 weeks. Yankees bats are heating up.',
    result: 'pending',
    game_date: daysAhead(1),
    units: 1.0,
  },
  {
    id: '7',
    sport: 'NFL',
    game: 'Philadelphia Eagles vs New York Giants',
    home_team: 'New York Giants',
    away_team: 'Philadelphia Eagles',
    bet_type: 'spread',
    pick: 'Eagles -7',
    odds: -110,
    confidence: 4,
    analysis: 'Hurts returns from injury. Eagles won 5 straight vs NFC East opponents. Giants starting QB on injury report. Eagles run game dominates in divisional play.',
    result: 'pending',
    game_date: daysAhead(2),
    units: 1.5,
  },
  {
    id: '8',
    sport: 'NBA',
    game: 'Denver Nuggets vs Phoenix Suns',
    home_team: 'Phoenix Suns',
    away_team: 'Denver Nuggets',
    bet_type: 'spread',
    pick: 'Nuggets -5',
    odds: -110,
    confidence: 3,
    analysis: 'Jokic triple-double machine at altitude. Suns are 5-12 ATS on the road this season. Nuggets have won 8 straight at home vs Western Conference opponents.',
    result: 'pending',
    game_date: daysAhead(1),
    units: 1.0,
  },
];

export const mockProps: Prop[] = [
  {
    id: '1',
    sport: 'NFL',
    player: 'Patrick Mahomes',
    team: 'Kansas City Chiefs',
    stat: 'Passing Yards',
    line: 287.5,
    over_odds: -115,
    under_odds: -105,
    recommendation: 'over',
    confidence: 5,
    game_date: daysAhead(1),
    opponent: 'Baltimore Ravens',
    result: 'pending',
  },
  {
    id: '2',
    sport: 'NFL',
    player: 'Tyreek Hill',
    team: 'Miami Dolphins',
    stat: 'Receiving Yards',
    line: 92.5,
    over_odds: -120,
    under_odds: +100,
    recommendation: 'over',
    confidence: 4,
    game_date: daysAhead(1),
    opponent: 'New England Patriots',
    result: 'pending',
  },
  {
    id: '3',
    sport: 'NBA',
    player: 'LeBron James',
    team: 'Los Angeles Lakers',
    stat: 'Points',
    line: 24.5,
    over_odds: -110,
    under_odds: -110,
    recommendation: 'over',
    confidence: 4,
    game_date: fmt(today),
    opponent: 'Golden State Warriors',
    result: 'pending',
  },
  {
    id: '4',
    sport: 'NBA',
    player: 'Stephen Curry',
    team: 'Golden State Warriors',
    stat: 'Three-Pointers Made',
    line: 4.5,
    over_odds: +110,
    under_odds: -130,
    recommendation: 'under',
    confidence: 3,
    game_date: fmt(today),
    opponent: 'Los Angeles Lakers',
    result: 'pending',
  },
  {
    id: '5',
    sport: 'MLB',
    player: 'Shohei Ohtani',
    team: 'Los Angeles Dodgers',
    stat: 'Strikeouts',
    line: 7.5,
    over_odds: -125,
    under_odds: +105,
    recommendation: 'over',
    confidence: 5,
    game_date: daysAhead(2),
    opponent: 'San Francisco Giants',
    result: 'pending',
  },
  {
    id: '6',
    sport: 'NFL',
    player: 'Josh Allen',
    team: 'Buffalo Bills',
    stat: 'Rushing Yards',
    line: 42.5,
    over_odds: -105,
    under_odds: -115,
    recommendation: 'over',
    confidence: 4,
    game_date: daysAhead(2),
    opponent: 'Miami Dolphins',
    result: 'pending',
  },
  {
    id: '7',
    sport: 'NBA',
    player: 'Nikola Jokic',
    team: 'Denver Nuggets',
    stat: 'Rebounds',
    line: 12.5,
    over_odds: -105,
    under_odds: -115,
    recommendation: 'over',
    confidence: 4,
    game_date: daysAhead(1),
    opponent: 'Phoenix Suns',
    result: 'pending',
  },
  {
    id: '8',
    sport: 'NBA',
    player: 'Jayson Tatum',
    team: 'Boston Celtics',
    stat: 'Points + Assists',
    line: 36.5,
    over_odds: -110,
    under_odds: -110,
    recommendation: 'over',
    confidence: 5,
    game_date: daysAgo(2),
    opponent: 'Milwaukee Bucks',
    result: 'win',
  },
];

export const mockOdds: OddsEntry[] = [
  {
    id: '1',
    sport: 'NFL',
    home_team: 'Baltimore Ravens',
    away_team: 'Kansas City Chiefs',
    game_date: daysAhead(1),
    game_time: '4:25 PM ET',
    spread_home: 3.0,
    spread_away: -3.0,
    spread_home_odds: -110,
    spread_away_odds: -110,
    moneyline_home: +135,
    moneyline_away: -155,
    total: 47.5,
    over_odds: -110,
    under_odds: -110,
  },
  {
    id: '2',
    sport: 'NFL',
    home_team: 'New York Giants',
    away_team: 'Philadelphia Eagles',
    game_date: daysAhead(2),
    game_time: '8:20 PM ET',
    spread_home: 7.0,
    spread_away: -7.0,
    spread_home_odds: -110,
    spread_away_odds: -110,
    moneyline_home: +240,
    moneyline_away: -290,
    total: 44.0,
    over_odds: -110,
    under_odds: -110,
  },
  {
    id: '3',
    sport: 'NBA',
    home_team: 'Golden State Warriors',
    away_team: 'Los Angeles Lakers',
    game_date: fmt(today),
    game_time: '10:00 PM ET',
    spread_home: -3.5,
    spread_away: 3.5,
    spread_home_odds: -110,
    spread_away_odds: -110,
    moneyline_home: -165,
    moneyline_away: +145,
    total: 224.5,
    over_odds: -110,
    under_odds: -110,
  },
  {
    id: '4',
    sport: 'NBA',
    home_team: 'Phoenix Suns',
    away_team: 'Denver Nuggets',
    game_date: daysAhead(1),
    game_time: '9:00 PM ET',
    spread_home: 5.0,
    spread_away: -5.0,
    spread_home_odds: -110,
    spread_away_odds: -110,
    moneyline_home: +190,
    moneyline_away: -225,
    total: 220.0,
    over_odds: -110,
    under_odds: -110,
  },
  {
    id: '5',
    sport: 'MLB',
    home_team: 'Houston Astros',
    away_team: 'New York Yankees',
    game_date: daysAhead(1),
    game_time: '7:10 PM ET',
    spread_home: 1.5,
    spread_away: -1.5,
    spread_home_odds: -135,
    spread_away_odds: +115,
    moneyline_home: -145,
    moneyline_away: +125,
    total: 8.5,
    over_odds: -115,
    under_odds: -105,
  },
  {
    id: '6',
    sport: 'NHL',
    home_team: 'Edmonton Oilers',
    away_team: 'Colorado Avalanche',
    game_date: daysAhead(1),
    game_time: '9:00 PM ET',
    spread_home: 0.5,
    spread_away: -0.5,
    spread_home_odds: -110,
    spread_away_odds: -110,
    moneyline_home: +105,
    moneyline_away: -120,
    total: 6.5,
    over_odds: -115,
    under_odds: -105,
  },
  {
    id: '7',
    sport: 'NBA',
    home_team: 'Milwaukee Bucks',
    away_team: 'Boston Celtics',
    game_date: daysAhead(3),
    game_time: '7:30 PM ET',
    spread_home: 4.5,
    spread_away: -4.5,
    spread_home_odds: -110,
    spread_away_odds: -110,
    moneyline_home: +175,
    moneyline_away: -210,
    total: 218.5,
    over_odds: -110,
    under_odds: -110,
  },
  {
    id: '8',
    sport: 'NFL',
    home_team: 'Dallas Cowboys',
    away_team: 'San Francisco 49ers',
    game_date: daysAhead(4),
    game_time: '4:25 PM ET',
    spread_home: -1.5,
    spread_away: 1.5,
    spread_home_odds: -110,
    spread_away_odds: -110,
    moneyline_home: +130,
    moneyline_away: -150,
    total: 49.0,
    over_odds: -115,
    under_odds: -105,
  },
];

export const mockTrackedBets: TrackedBet[] = [
  {
    id: '1',
    sport: 'NFL',
    description: 'Chiefs -3 vs Ravens',
    bet_type: 'spread',
    odds: -110,
    units: 2.0,
    result: 'win',
    profit: 1.82,
    date: daysAgo(3),
  },
  {
    id: '2',
    sport: 'NFL',
    description: '49ers ML vs Cowboys',
    bet_type: 'moneyline',
    odds: -145,
    units: 1.5,
    result: 'win',
    profit: 1.03,
    date: daysAgo(3),
  },
  {
    id: '3',
    sport: 'NBA',
    description: 'Lakers/Warriors Over 224.5',
    bet_type: 'over/under',
    odds: -110,
    units: 1.0,
    result: 'loss',
    profit: -1.0,
    date: daysAgo(2),
  },
  {
    id: '4',
    sport: 'NBA',
    description: 'Celtics -4.5 vs Bucks',
    bet_type: 'spread',
    odds: -110,
    units: 2.0,
    result: 'win',
    profit: 1.82,
    date: daysAgo(2),
  },
  {
    id: '5',
    sport: 'NHL',
    description: 'Avalanche ML vs Oilers',
    bet_type: 'moneyline',
    odds: -120,
    units: 1.0,
    result: 'loss',
    profit: -1.0,
    date: daysAgo(1),
  },
];
